import type { Metadata } from "next";
import "@/styles/global.scss"
import { AuthProvider } from "@/contexts/Auth";
import { ToastProvider } from "@/contexts/Toast";

export const metadata: Metadata = {
  title: "Forex trading",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
