include:
  - ../postgres/docker-compose.yaml
  - ../redis/docker-compose.yaml

services:
  server:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}