import i18next from "../../i18n/i18next";
import type { Metadata } from "next";

import { AuthProvider } from "@/contexts/Auth";
import { ToastProvider } from "@/contexts/Toast";
import { Language, supportedLngs } from "@/i18n/language";

import "@/styles/global.scss";

export function generateStaticParams() {
  return supportedLngs
}

export const metadata: Metadata = {
  title: "Forex trading",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<Language>
}>) {
  const { code } = await params
  return (
    <html lang={code}>
      <body>
        <ToastProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
